os: osx
language: generic
before_install:
- brew install python
install:
- pip3 install -r requirements.txt
script:
- python3 setup.py py2app
before_deploy:
- cd dist && zip -9 -r V2Net.zip V2Net.app
deploy:
  provider: releases
  api_key:
    secure: ${GH_TOKEN}
  file: "./dist/V2Net.zip"
  skip_cleanup: true
  on:
    repo: deepjia/v2net
    tags: true
